### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by bklavet** [kainoa21/alexa-directtv-remote#1]
Hello, are you using the Index.js as a aws lambda function?

I have been trying to do something similar but have been unsuccessful so far.

**Comment by kainoa21** [comment]
Yes, this does work as an aws lambda function.  You need to make sure that the main property in your package.json is set and then you have to zip up all of the source and upload the zip file to lambda.

**Comment by bklavet** [comment]
Thanks for that.  I was not including the package.json.  I will give it another shot.  Thanks again.  I like what you did for the switch case arguments.  Are you able to tune your receiver by giving a full channel?  Example "tune to channel 202"  or does each digit have to be individually done, "press 2, press 0, press 2?

**Comment by kainoa21** [comment]
Yes, you can give a full channel.  If you look in the utterances.json file you will see samples for single, double, and triple digit channels.  Alexa does a pretty good job of interpreting those and passing the full number for the given key.

**Comment by bklavet** [comment]
Leave a comment
